from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal
from uuid import UUID

from pydantic import Field, JsonValue, model_validator

from app.domain.models import Place, Route, SourceStatus
from app.schemas.constraint import Constraint
from app.schemas.trip import ContractModel, Trip
from app.services.planning import CandidateEndpointFact

from .contracts import Digest, OpaqueId, ProviderCandidateFactView, ProviderFactBundle


TrustedFactKind = Literal["PLACE", "ROUTE"]


def _trusted_primary_source(status: SourceStatus) -> bool:
    return status in {SourceStatus.ONLINE, SourceStatus.VERIFIED_CACHE}


def _validate_price_source(*, owner_status: SourceStatus, price_status: SourceStatus) -> None:
    if price_status is SourceStatus.UNKNOWN:
        return
    if price_status != owner_status or not _trusted_primary_source(price_status):
        raise ValueError("price provenance must come from the same Provider/cache fact")


class ProviderFactIssueDraft(ContractModel):
    """Internal-only input assembled from normalized Provider/cache results.

    This contract is deliberately not exposed as an HTTP request.  Fact IDs,
    the aggregate digest and the signed set ID are all generated by the server.
    """

    schema_version: Literal["1.0"] = "1.0"
    trip: Trip
    start_location: CandidateEndpointFact
    end_location: CandidateEndpointFact
    confirmed_constraints: tuple[Constraint, ...]
    confirmed_trip_summary: dict[str, JsonValue]
    places: tuple[Place, ...] = Field(min_length=6, max_length=8)
    routes: tuple[Route, ...] = Field(default_factory=tuple, max_length=64)

    @model_validator(mode="after")
    def validate_provider_boundary(self) -> "ProviderFactIssueDraft":
        city_code = self.trip.city_context.city_code
        if self.start_location.city_code != city_code:
            raise ValueError("startLocation must belong to the confirmed Trip city")
        if self.end_location.city_code != city_code:
            raise ValueError("endLocation must belong to the confirmed Trip city")
        for endpoint in (self.start_location, self.end_location):
            if not _trusted_primary_source(endpoint.provenance.sourceStatus):
                raise ValueError("endpoint provenance must be ONLINE or VERIFIED_CACHE")

        place_ids: set[str] = set()
        trusted_points = {
            (self.start_location.location.longitude, self.start_location.location.latitude),
            (self.end_location.location.longitude, self.end_location.location.latitude),
        }
        for place in self.places:
            if place.placeId in place_ids:
                raise ValueError("places must use unique Provider placeId values")
            place_ids.add(place.placeId)
            if place.cityCode != city_code:
                raise ValueError("all places must belong to the confirmed Trip city")
            if not _trusted_primary_source(place.provenance.sourceStatus):
                raise ValueError("place provenance must be ONLINE or VERIFIED_CACHE")
            _validate_price_source(
                owner_status=place.provenance.sourceStatus,
                price_status=place.priceReference.provenance.sourceStatus,
            )
            trusted_points.add((place.location.longitude, place.location.latitude))

        route_ids: set[str] = set()
        for route in self.routes:
            if route.routeId in route_ids:
                raise ValueError("routes must use unique Provider routeId values")
            route_ids.add(route.routeId)
            if not _trusted_primary_source(route.provenance.sourceStatus):
                raise ValueError("route provenance must be ONLINE or VERIFIED_CACHE")
            _validate_price_source(
                owner_status=route.provenance.sourceStatus,
                price_status=route.priceReference.provenance.sourceStatus,
            )
            origin = (route.origin.longitude, route.origin.latitude)
            destination = (route.destination.longitude, route.destination.latitude)
            if origin not in trusted_points or destination not in trusted_points:
                raise ValueError("route endpoints must resolve to signed endpoint/place facts")
        return self


class ProviderFactReferenceSummary(ContractModel):
    fact_ref_id: OpaqueId
    kind: TrustedFactKind
    provider_object_id: OpaqueId
    payload_digest: Digest
    source_status: SourceStatus
    fetched_at: datetime
    is_stale: bool


class ProviderFactSetSummary(ContractModel):
    schema_version: Literal["1.0"] = "1.0"
    fact_set_id: OpaqueId
    provider_fact_digest: Digest
    trip_id: UUID
    issued_at: datetime
    references: tuple[ProviderFactReferenceSummary, ...] = Field(min_length=6)


class ProviderFactSnapshot(ContractModel):
    """Full immutable server snapshot; never accepted from the browser or LLM."""

    schema_version: Literal["1.0"] = "1.0"
    fact_set_id: OpaqueId
    provider_fact_digest: Digest
    issued_at: datetime
    draft: ProviderFactIssueDraft
    references: tuple[ProviderFactReferenceSummary, ...] = Field(min_length=6)

    def as_bundle(self) -> ProviderFactBundle:
        places_by_id = {item.placeId: item for item in self.draft.places}
        place_refs = [item for item in self.references if item.kind == "PLACE"]
        candidates = tuple(
            ProviderCandidateFactView(
                place_fact_id=reference.fact_ref_id,
                provider_place_id=reference.provider_object_id,
                name=places_by_id[reference.provider_object_id].name,
                category=places_by_id[reference.provider_object_id].category or "PLACE",
                source_status=reference.source_status,
                fact_digest=reference.payload_digest,
                known_attributes={
                    "cityCode": places_by_id[reference.provider_object_id].cityCode,
                    "fetchedAt": reference.fetched_at.isoformat(),
                    "isStale": reference.is_stale,
                    "priceAmountCents": places_by_id[
                        reference.provider_object_id
                    ].priceReference.amountCents,
                    "priceSourceStatus": places_by_id[
                        reference.provider_object_id
                    ].priceReference.provenance.sourceStatus.value,
                },
            )
            for reference in place_refs
        )
        return ProviderFactBundle(
            fact_set_id=self.fact_set_id,
            provider_fact_digest=self.provider_fact_digest,
            trip=self.draft.trip,
            start_location=self.draft.start_location,
            end_location=self.draft.end_location,
            confirmed_constraints=self.draft.confirmed_constraints,
            confirmed_trip_summary=self.draft.confirmed_trip_summary,
            candidate_facts=candidates,
        )

    def summary(self) -> ProviderFactSetSummary:
        return ProviderFactSetSummary(
            fact_set_id=self.fact_set_id,
            provider_fact_digest=self.provider_fact_digest,
            trip_id=self.draft.trip.trip_id,
            issued_at=self.issued_at,
            references=self.references,
        )


__all__ = [
    "ProviderFactIssueDraft",
    "ProviderFactReferenceSummary",
    "ProviderFactSetSummary",
    "ProviderFactSnapshot",
    "TrustedFactKind",
]
